insert into KOKETJO.DEMO_ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC, ACCOUNT_TYPE_NAME, CREATION_DATE)
values (5000, 'MILES', 'Miles', TO_DATE('2020/01/01', 'YYYY/MM/DD'));
insert into KOKETJO.DEMO_ACCOUNT_TYPE (ACCOUNT_TYPE_ID, MNEMONIC, ACCOUNT_TYPE_NAME, CREATION_DATE)
values (5001, 'PLAY', 'Game Play', TO_DATE('2021/03/01', 'YYYY/MM/DD'));