CREATE SCHEMA KOKETJO;

CREATE SEQUENCE KOKETJO.KOKE_TJO_GENERIC_SEQ
    START WITH 5001
    INCREMENT BY 1;

CREATE TABLE KOKETJO.DEMO_ACCOUNT_TYPE
(
    ACCOUNT_TYPE_ID BIGINT NOT NULL,
    MNEMONIC VARCHAR(100) NOT NULL UNIQUE,
    ACCOUNT_TYPE_NAME VARCHAR(255) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    PRIMARY KEY(ACCOUNT_TYPE_ID)
);

CREATE TABLE KOKETJO.DEMO_ACCOUNT_TX
(
    ACCOUNT_TX_ID BIGINT NOT NULL,
    ACCOUNT_TYPE_ID BIGINT NOT NULL,
    MEMBER_ID BIGINT NOT NULL,
    AMOUNT BIGINT NOT NULL,
    TX_DATE DATE NOT NULL,
    PRIMARY KEY (ACCOUNT_TX_ID),
    CONSTRAINT ACCOUNT_TYPE_ID_FK FOREIGN KEY (ACCOUNT_TX_ID) REFERENCES KOKETJO.DEMO_ACCOUNT_TYPE (ACCOUNT_TYPE_ID),
);

CREATE TABLE KOKETJO.DEMO_ACCOUNT_TX_DETAILS
(
    ACCOUNT_TX_DETAILS_ID BIGINT NOT NULL,
    ACCOUNT_TX_ID BIGINT NOT NULL,
    PARTNER_NAME VARCHAR(255) NOT NULL,
    NUMBER_OF_ITEMS BIGINT NOT NULL,
    PRIMARY KEY(ACCOUNT_TX_DETAILS_ID),
    CONSTRAINT ACCOUNT_TX_ID_FK FOREIGN KEY (ACCOUNT_TX_ID) REFERENCES KOKETJO.DEMO_ACCOUNT_TX(ACCOUNT_TX_ID)
);